{% set name = "dadi" %}
{% set version = "2.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e93eba38612856b72cbfeaa320148a99ad50d8e7f03bee9bddd181880735144f

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - pip
    - cython
    - python
    - numpy
    - nlopt
  run:
    - python
    - scipy
    - matplotlib-base
    - nlopt

test:
  imports:
    - dadi
    - dadi.DFE
    - dadi.Triallele
    - dadi.TwoLocus

about:
  home: https://bitbucket.org/gutenkunstlab/dadi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Fit population genetic models using diffusion approximations to the allele frequency spectrum
  doc_url: https://dadi.readthedocs.io/

extra:
  recipe-maintainers:
    - tjstruck
    - RyanGutenkunst
